export type Listing = {
  id: string;
  title: string;
  city: string;
  state: string;
  price: number;
  priceType: 'sale' | 'rent';
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  propertyType: string;
  images: string[];
  featured: boolean;
  reviewCount: number;
  rating: number;
  description: string;
  whatsapp?: string;
};

export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'Modern Luxury Villa',
    city: 'Los Angeles',
    state: 'CA',
    price: 2850000,
    priceType: 'sale',
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4200,
    propertyType: 'villa',
    images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800'],
    featured: true,
    reviewCount: 48,
    rating: 4.9,
    description: 'Stunning modern villa with panoramic city views, infinity pool, and smart home technology throughout.',
  },
  {
    id: '2',
    title: 'Luxury Penthouse',
    city: 'New York',
    state: 'NY',
    price: 12500,
    priceType: 'rent',
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2800,
    propertyType: 'apartment',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    featured: true,
    reviewCount: 92,
    rating: 4.8,
    description: 'Sky-high penthouse in Midtown Manhattan with floor-to-ceiling windows and private rooftop terrace.',
  },
  {
    id: '3',
    title: 'Mountain View Estate',
    city: 'Aspen',
    state: 'CO',
    price: 4200000,
    priceType: 'sale',
    bedrooms: 6,
    bathrooms: 5,
    sqft: 6100,
    propertyType: 'house',
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800'],
    featured: true,
    reviewCount: 34,
    rating: 5.0,
    description: 'Breathtaking mountain estate with ski-in/ski-out access, chef kitchen, and heated outdoor spaces.',
  },
  {
    id: '4',
    title: 'Beachfront Retreat',
    city: 'Miami',
    state: 'FL',
    price: 3100000,
    priceType: 'sale',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3500,
    propertyType: 'villa',
    images: ['https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800'],
    featured: true,
    reviewCount: 67,
    rating: 4.7,
    description: 'Direct ocean frontage with private beach, pool, and open-plan living spaces.',
  },
  {
    id: '5',
    title: 'Downtown Loft',
    city: 'Austin',
    state: 'TX',
    price: 4200,
    priceType: 'rent',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1600,
    propertyType: 'apartment',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    featured: false,
    reviewCount: 28,
    rating: 4.6,
    description: 'Industrial-chic loft in the heart of downtown Austin with exposed brick and city views.',
  },
  {
    id: '6',
    title: 'Suburban Family Home',
    city: 'San Francisco',
    state: 'CA',
    price: 1850000,
    priceType: 'sale',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2900,
    propertyType: 'house',
    images: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800'],
    featured: true,
    reviewCount: 41,
    rating: 4.8,
    description: 'Beautifully renovated craftsman home in a top-rated school district with large backyard.',
  },
  {
    id: '7',
    title: 'Waterfront Condo',
    city: 'Seattle',
    state: 'WA',
    price: 1250000,
    priceType: 'sale',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1800,
    propertyType: 'condo',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
    featured: false,
    reviewCount: 19,
    rating: 4.5,
    description: 'Stunning waterfront condo with Puget Sound views and resort-style amenities.',
  },
  {
    id: '8',
    title: 'Historic Brownstone',
    city: 'Boston',
    state: 'MA',
    price: 2400000,
    priceType: 'sale',
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3800,
    propertyType: 'house',
    images: ['https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'],
    featured: false,
    reviewCount: 55,
    rating: 4.9,
    description: 'Meticulously restored Victorian brownstone with original details and modern upgrades.',
  },
];
